# Generated by Django 3.2.4 on 2021-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
