# Generated by Django 3.2.4 on 2021-06-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_joined_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
