# Generated by Django 3.2.4 on 2021-06-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
