# Generated by Django 3.2.4 on 2021-06-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('task', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('room_code', models.CharField(max_length=200)),
            ],
        ),
    ]
