# Generated by Django 3.2.4 on 2021-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_upload_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_task',
            name='task',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
