# Generated by Django 3.2.4 on 2021-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_joined_classroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='classroom_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
