# Generated by Django 3.2.4 on 2021-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_room_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.AddField(
            model_name='upload_task',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
