# Generated by Django 3.2.4 on 2021-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='classroom_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='room_images'),
        ),
    ]
