# Generated by Django 3.2.4 on 2021-06-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20210616_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joined',
            name='classroom_image',
        ),
    ]
