# Generated by Django 3.2.4 on 2021-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_joined_classroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='classroom_image',
            field=models.ImageField(null=True, upload_to='Joined'),
        ),
        migrations.AlterField(
            model_name='upload_task',
            name='file',
            field=models.FileField(blank=True, upload_to='tasks'),
        ),
    ]
