# Generated by Django 3.2.4 on 2021-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_auto_20210618_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='classroom_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
