# Generated by Django 3.2.4 on 2021-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0023_alter_joined_classroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joined',
            name='classroom_image',
            field=models.ImageField(null=True, upload_to='Joined'),
        ),
    ]
