# Generated by Django 3.2.4 on 2021-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_auto_20210624_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='room_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
