# Generated by Django 3.2.4 on 2021-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
