# Generated by Django 3.2.4 on 2021-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0034_upload_task_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_task',
            name='task_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
