# Generated by Django 3.2.4 on 2021-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0035_upload_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_task',
            name='task_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
