# Generated by Django 3.2.4 on 2021-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0036_alter_upload_task_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTaskFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='tasks')),
                ('task_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload_task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload_task',
            name='task_number',
        ),
    ]
