# Generated by Django 3.2.4 on 2021-07-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
    ]
