# Generated by Django 3.2.4 on 2021-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0041_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='task_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
