# Generated by Django 4.0.4 on 2022-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0043_alter_mark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
