# Generated by Django 4.0.4 on 2022-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0045_remove_joined_classroom_image_joined_classroom_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_task',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
